### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by rob313663** [TanukiSharp/ReedSolomon#3]
For exemple, -> For example,
depends on the amound of -> depends on the amount

**Comment by TanukiSharp** [comment]
Thank you for the typos, I fixed them.
As for the `int[]` to `byte[]` thing, yes it's terrible in term of perfs, actually even the base implementation is garbage in term of perfs.
It was a naive port from the Java ZXing library. The LINQ was just to get a super quick implementation for someone who needed it.

**Comment by rob313663** [comment]
Ok, I am just learning Reed-Solomon and came across your project.

/rob
